### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-intellij-plugin#10]
Showing the tools menu caused an error. ( Android Studio/Mac )

Event log:
2:26:06 PM Plugin Error: PhoneGap threw an uncaught NullPointerException. Disable Plugin
2:26:06 PM NullPointerException: update failed for AnAction with ID=PhoneGap.Init

**Comment by imhotep** [comment]
reproduction steps please?

**Comment by purplecabbage** [comment]
1. Click the 'Tools' button in the title menu
2. Plugin Error

**Comment by macdonst** [comment]
I get that now too. I did update some "android" packages today.

`NullPointerException: update failed for AnAction with ID=PhoneGap.Init`

**Comment by infil00p** [comment]
Here's the stack trace:
```
update failed for AnAction with ID=PhoneGap.Init
java.lang.NullPointerException
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:34)
	at PhoneGapInit.update(PhoneGapInit.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:120)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:265)
	at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:239)
	at com.intellij.openapi.actionSystem.impl.Utils.hasEnabledChildren(Utils.java:209)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:147)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:135)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevengill** [comment]
I have the same problem when I click initialize Project from the plugin. 

Started by creating a new empty activity project. Then i go to the plugin and it gives me this error. Doesn't actually add the files.

I am using android studio 2.3, plugman 1.4.1 on my machine. Updated my android packages.

**Comment by imhotep** [comment]
Thanks. Looking into it. Only happens when SDK/Tools update right?

**Comment by stevengill** [comment]
For me, it happened on first run. But all my shit is up to date. I've tried uninstalling, reinstalling it too. I haven't been able to get it working once

**Comment by infil00p** [comment]
It's always going to happen on First Run.  IntelliJ calls update and sends that out to the plugins, which all go out and check.  When the check happens, that's when the plugin fails.  This is a very easy problem to reproduce on Android Studio, you literally just wait for it to fail once you start up Android Studio.

**Comment by imhotep** [comment]
Should be fixed
